// estruturas.h com referencia na propria documentacao da jvm; tudo faz parte do ClassFile Format item 4 do site
//(https://docs.oracle.com/javase/specs/jvms/se7/html/)
#ifndef	ESTRUTURAS_H
#define ESTRUTURAS_H

#include <stdio.h>
#include <stdint.h>

typedef uint8_t u1;     //uint8_t       valor da direita representa o numero de bytes.. 1 byte (8bits)
typedef uint16_t u2;    //uint16_t      2 bytes (16bits)
typedef uint32_t u4;    //uint32_t      4 bytes (32bits)

#define MAX_U1 255           // valor maximo para uint8_t
#define MAX_U2 65535         // valor maximo para uint16_t
#define MAX_U4 2147483647    // valor maximo para uint32_t


//      abaixo temos a Constant Pool -> contem as constantes que sao necessarias para rodar o codigo das classes
//      tipo de informacao eh definida pelo byte evidenciado.
//      https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.4
typedef struct cp_info{
	u1 tag;
	union{ 
		struct CONSTANT_Class{
			u2 name_index;
		}CONSTANT_Class;

		struct CONSTANT_Fieldref{
			u2 class_index;
			u2 name_and_type_index;
		}CONSTANT_Fieldref;

		struct CONSTANT_Methodref{
			u2 class_index;
			u2 name_and_type_index;
		}CONSTANT_Methodref;
		
		struct CONSTANT_InterfaceMethodref{
			u2 class_index;
			u2 name_and_type_index;
		}CONSTANT_InterfaceMethodref;
		
		struct CONSTANT_Integer{
			u4 bytes;
		}CONSTANT_Integer;

		struct CONSTANT_Long{
			u4 high_bytes;
			u4 low_bytes;
		}CONSTANT_Long;

		struct CONSTANT_Double{
			u4 high_bytes;
			u4 low_bytes;
		}CONSTANT_Double;
		
		struct CONSTANT_Float{
			u4 bytes;
		}CONSTANT_Float;

		struct CONSTANT_String{
			u2 string_index;
		}CONSTANT_String;
		
		struct CONSTANT_NameAndType{
			u2 name_index;
			u2 descriptor_index;
		}CONSTANT_NameAndType;

		struct CONSTANT_MethodHandle{
			u1 reference_kind;
			u2 reference_index;
		}CONSTANT_MethodHandle;

		struct CONSTANT_MethodType{
			u2 descriptor_index;
		}CONSTANT_MethodType;
		
		struct CONSTANT_InvokeDynamicInfo{
			u2 bootstrap_method_attr_index;
    		u2 name_and_type_index;
		}CONSTANT_InvokeDynamicInfo;

		struct CONSTANT_UTF8{
			u2 length;
			u1 *bytes;
		}CONSTANT_UTF8;

	}UnionCP;

}cp_info;

//flags de acesso java virtual machine
//retirado do seguinte site: https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.5
//flags em numero inteiro e definicoes

enum access_flags{
	ACC_PUBLIC = 1,				    //Declared public; may be accessed from outside its package.
	ACC_PRIVATE = 2,			    //Declared private; usable only within the defining class.
	ACC_PROTECTED = 4,			    //Declared protected; may be accessed within subclasses.
	ACC_STATIC = 8,				    //Declared static.
	ACC_FINAL = 16,				    //Declared final; never directly assigned to after object construction
	ACC_SYNCHRONIZED = 32,		    //Declared synchronized; invocation is wrapped by a monitor use
	ACC_BRIDGE = 64,			    //A bridge method, generated by the compiler.
	ACC_VARARGS = 128,			    //Declared with variable number of arguments.
	ACC_NATIVE = 256,			    //Declared native; implemented in a language other than Java.
	ACC_ABSTRACT = 1024,		    //Declared abstract; no implementation is provided.
	ACC_STRICT = 2048,			    //Declared strictfp; floating-point mode is FP-strict.
	ACC_SYNTHETIC = 4096,		    //Declared synthetic; not present in the source code.
	ACC_ENUM = 16384,               //Declared as an element of an enum.
	ACC_VOLATILE = 64,			    //Declared volatile; cannot be cached.
	ACC_TRANSIENT = 128             //Declared transient; not written or read by a persistent object manager.
};

/**
 * pool de constantes
 * tipos válidos de tags
 * https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.4
 */
enum constant_pool_tags{
	CONSTANT_Class = 7,
	CONSTANT_Fieldref = 9,
	CONSTANT_Methodref = 10,
	CONSTANT_InterfaceMethodref = 11,
	CONSTANT_String = 8,
	CONSTANT_Integer = 3,
	CONSTANT_Float = 4,
	CONSTANT_Long = 5,
	CONSTANT_Double = 6,
	CONSTANT_NameAndType = 12,
	CONSTANT_Utf8 = 1,
	CONSTANT_MethodHandle = 15,
	CONSTANT_MethodType = 16,
	CONSTANT_InvokeDynamic = 18
};


typedef struct attribute_info {
	u2 attribute_name_index;
	u4 attribute_length;
	void *info;
}attribute_info;

typedef struct field_info{
	u2 access_flags;
	u2 name_index;
	u2 descriptor_index;
	u2 attributes_count;
	attribute_info ** attributes;
}field_info;

typedef struct exception_table{
	u2 start_pc;
    u2 end_pc;
    u2 handler_pc;
    u2 catch_type;
}exception_table;


typedef struct line_number_tableInfo {
	u2 start_pc;
	u2 line_number;
}line_number_tableInfo;

typedef struct line_number_table {
	u2 line_number_table_length;
	line_number_tableInfo * info;
}line_number_table;

typedef struct code_attribute {
  u2 max_stack;
  u2 max_locals;
  u4 code_length;
  u1 * code;
  u2 exception_table_length;
  exception_table * table; 
  u2 attributes_count;
	attribute_info ** attributes;
}code_attribute;

typedef struct method_info{
	u2 access_flags;
	u2 name_index;
	u2 descriptor_index;
	u2 attributes_count;
	attribute_info ** attributes;
}method_info;

typedef struct source_file_attribute {
	u2 attribute_name_index;
	u4 attribute_length;
	u2 source_file_index;
}source_file_attribute;

typedef struct constantValue_attribute {
    u2 constantvalue_index;
}constantValue_attribute;

typedef struct exceptions_attribute {
	u2 attribute_name_index;
	u4 attribute_length;
	u2 number_of_exceptions;
	u2 *exception_index_table; 	// [number_of_exceptions]
}exceptions_attribute;

typedef struct classes {
	u2 inner_class_info_index;
	u2 outer_class_info_index;	
	u2 inner_name_index;		
	u2 inner_class_access_flags; 
}classes;

typedef struct innerClasses_attribute{
	u2 attribute_name_index;
	u4 attribute_length;
	u2 number_of_classes;
	classes ** classes_vector; 	
}innerClasses_attribute;

typedef struct enclosingMethod_attribute {
	u2 class_index;			
	u2 method_index;	
}enclosingMethod_attribute;

typedef struct signature_attribute {
	u2 signature_index;
}signature_attribute;

typedef struct sourceDebugExtension_attribute {
	u1 * debug_extension; 	
}sourceDebugExtension_attribute;

typedef struct local_variable_table {
	u2 start_pc;
	u2 length;
	u2 name_index;
	u2 descriptor_index;
	u2 index;
}local_variable_table;

typedef struct localVariableTable_attributes {
	u2 attribute_name_index;
	u4 attribute_length;
	u2 local_variable_table_length;
	local_variable_table *local_variables; 
}localVariableTable_attributes;

typedef struct localVariableTypeTable {
	u2 local_variable_type_table_length;
	local_variable_table *local_variables; 
}localVariableTypeTable;

struct annotation;
struct element_value;


//https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7
typedef struct element_value{

	u1 tag;
	union{

		u2 const_value_index;
		u2 outer_class_info_index;

		struct annotation *annotation_value;	

		struct {

			u2 type_name_index;
			u2 const_name_index;

		} enum_const_index;

		struct {

			u2 num_values;
			struct element_value *element_values;

		} array_value;

	} value;

}element_value;


struct element_value_pairs {

	u2 element_name_index;
	element_value value;

};
typedef struct element_value_pairs element_value_pairs;


struct annotation {

	u2 type_index;
	u2 num_element_value_pairs;
	element_value_pairs *elementes_pairs;

};
typedef struct annotation annotation;


struct runTimeVisibleAnnotations_attribute {

	u2 num_annotations;
	annotation *annotations;


};
typedef struct runTimeVisibleAnnotations_attribute runTimeVisibleAnnotations_attribute;


struct runTimeInvisibleAnnotations_attribute {

	u2 num_annotations;
	annotation *annotations;

};
typedef struct runTimeInvisibleAnnotations_attribute runTimeInvisibleAnnotations_attribute;


struct parameter_annotations {	

	u2 num_annotations;
	annotation *annotations;	


};
typedef struct parameter_annotations parameter_annotations;


struct runtimeVisibleParameterAnnotations_attribute {

    u1 num_parameters;
    parameter_annotations *parameters_annotations;	

};
typedef struct runtimeVisibleParameterAnnotations_attribute runtimeVisibleParameterAnnotations_attribute;



struct runtimeInvisibleParameterAnnotations_attribute {

    u1 num_parameters;
	parameter_annotations *parameters_annotations;

};
typedef struct runtimeInvisibleParameterAnnotations_attribute runtimeInvisibleParameterAnnotations_attribute;


struct annotationDefault_attribute {

    element_value default_value;

};
typedef struct annotationDefault_attribute annotationDefault_attribute;

struct bootstrap_methods {

	u2 bootstrap_method_ref;
	u2 num_bootstrap_arguments;
    u2 *bootstrap_arguments;		


};
typedef struct bootstrap_methods bootstrap_methods;


struct bootstrapMethods_attribute {

    u2 num_bootstrap_methods;

    bootstrap_methods *bt_methods; 

};
typedef struct bootstrapMethods_attribute bootstrapMethods_attribute;


//https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7.4
struct verification_type_info{

	u1 tag;

	union{

		struct {

		} top_variable_info;

		struct {

		} integer_variable_info;

		struct {

		} float_variable_info;

		struct {

		} long_variable_info;

		struct{

		} double_variable_info;

		struct {
		} null_variable_info;

		struct {

		} uninitializedThis_variable_info;
		struct {
			u2 cpool_index;

		} object_variable_info;

		struct {
			u2 offset; 

		} uninitialized_variable_info;


	} type_info;

};
typedef struct verification_type_info verification_type_info;

//stack map frame
//https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7.4
struct stack_map_frame {
	u1 frame_type;
	union{
		struct{

		} same_frame;

		struct{
			
			verification_type_info ** stack; 

		} same_locals_1_stack_item_frame;

		struct{

			u2 offset_delta;
    	verification_type_info ** stack; 

		} same_locals_1_stack_item_frame_extended;

		struct{
			u2 offset_delta;

		} chop_frame;

		struct{
			u2 offset_delta;

		} same_frame_extended;

		struct{

			u2 offset_delta;
			verification_type_info ** locals;

		} append_frame;

		struct{
    	u2 offset_delta;
    	u2 number_of_locals;
    	verification_type_info ** locals; 
    	u2 number_of_stack_items;
    	verification_type_info ** stack; 
		} full_frame;
	} map_frame_type;
};
typedef struct stack_map_frame stack_map_frame;

// Stack Map table attribute
//https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7.4
struct stackMapTable_attribute {
    u2 number_of_entries;
    stack_map_frame ** entries;
};
typedef struct stackMapTable_attribute stackMapTable_attribute;

#endif
